// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9EgikbX3xeObQ52RiVY3gB2bN3JmDYck',
    appId: '1:365458530051:web:0756bd398b3c061d251336',
    messagingSenderId: '365458530051',
    projectId: 'taller-272',
    authDomain: 'taller-272.firebaseapp.com',
    storageBucket: 'taller-272.appspot.com',
    measurementId: 'G-9YD51NHVNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCetnZ2SeOCiMZg3V-eViSqK42Ht4NNRXY',
    appId: '1:365458530051:android:b744f4fb25acb265251336',
    messagingSenderId: '365458530051',
    projectId: 'taller-272',
    storageBucket: 'taller-272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKMm1bJAKcgDwlLzsLnJMLriXUphAyL8o',
    appId: '1:365458530051:ios:387e0d60c23ba377251336',
    messagingSenderId: '365458530051',
    projectId: 'taller-272',
    storageBucket: 'taller-272.appspot.com',
    iosClientId: '365458530051-90bfcve600pbjcf5u301v01j4uf9c1a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogTallerBaseDeDatos',
  );
}
